language: python
dist: xenial
sudo: false
python:
  - "3.5"
  - "3.6"
  - "3.7"
env:
  global:
    - MODULE=passaas
  matrix:
    - COVERAGE="false"
    - COVERAGE="true"
matrix:
  exclude:
    - python: "3.5"
      env: COVERAGE="true"  
    - python: "3.6"
      env: COVERAGE="true"
install: source ci/install.sh
script: bash ci/test.sh
after_success: source ci/success.sh