build: "off"

environment:
  matrix:
    - PYTHON_VERSION: "3.4"
      PYTHON: "C:\\Python34"
    - PYTHON_VERSION: "3.5"
      PYTHON: "C:\\Python35"
    - PYTHON_VERSION: "3.6"
      PYTHON: "C:\\Python36"
    - PYTHON_VERSION: "3.7"
      PYTHON: "C:\\Python37"

init:
  - "ECHO %PYTHON_VERSION%"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install --upgrade pip"
  - "pip install -r requirements.txt"
  - "pip install -r test-requirements.txt"
  - "pip install -e ."

test_script:
  - "python setup.py test"
  