swagger: "2.0"
info:
  description: Passaas API
  version: "1.0.0"
  title: Passwd as a Service
consumes:
  - application/json
produces:
  - application/json

basePath: /api
paths:
  /users:
    get:
      operationId: passaas.controllers.user_controller.fetch_all_users
      tags: [Users]
      summary: A list of all users on the system
      description: A list of all users on the system, as defined in the passwd file
      responses:
        200:
          description: Returns all users
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        404:
          description: No users
  /users/{uid}:
    get:
      tags: [Users]
      operationId: passaas.controllers.user_controller.fetch_user
      summary: Get a single user
      parameters:
        - $ref: '#/parameters/uid'
      responses:
        200:
          description: Return user
          schema:
            $ref: '#/definitions/User'
        404:
          description: User does not exist
  /users/query:
    get:
      tags: [Users]
      operationId: passaas.controllers.user_controller.query_users
      summary: Get a list of users matching the specified query
      parameters:
        - $ref: '#/parameters/name'
        - $ref: '#/parameters/quid'
        - $ref: '#/parameters/qgid'
        - $ref: '#/parameters/comment'
        - $ref: '#/parameters/home'
        - $ref: '#/parameters/shell'
      responses:
        200:
          description: Returns all users that match the query
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        404:
          description: No users matched the query
  /groups:
    get:
      operationId: passaas.controllers.group_controller.fetch_all_groups
      tags: [Groups]
      summary: A list of all groups on the system
      description: A list of all groups on the system, as defined in the group file
      responses:
        200:
          description: Returns all groups
          schema:
            type: array
            items:
              $ref: '#/definitions/Group'
        404:
          description: No groups
  /groups/{gid}:
    get:
      tags: [Groups]
      operationId: passaas.controllers.group_controller.fetch_group
      summary: Get a single group
      parameters:
        - $ref: '#/parameters/gid'
      responses:
        200:
          description: Return user
          schema:
            $ref: '#/definitions/Group'
        404:
          description: Group does not exist

parameters:
  uid:
    name: uid
    description: User identifier
    in: path
    type: integer
    required: true
  gid:
    name: gid
    description: Group identifier
    in: path
    type: integer
    required: true
  name:
    name: name
    description: User name
    in: query
    type: string
    required: false
  quid:
    name: uid
    description: User identifier
    in: query
    type: integer
    required: false
  qgid:
    name: gid
    description: Group identifier
    in: query
    type: integer
    required: false
  comment:
    name: comment
    description: Comment
    in: query
    type: string
    required: false
  home:
    name: home
    description: Home directory
    in: query
    type: string
    required: false
  shell:
    name: shell
    description: Shell
    in: query
    type: string
    required: false
definitions:
  User:
    type: object
    properties:
      name:
        type: string
        description: User name
        example: "root"
        readOnly: true
      uid:
        type: integer
        description: User identifier
        example: 123
        readOnly: true
      gid:
        type: integer
        description: Group identifier
        example: 123
        readOnly: true
      comment:
        type: string
        description: Comment
        example: "root"
        readOnly: true
      home:
        type: string
        description: home directory
        example: "/root"
        readOnly: true
      shell:
        type: string
        description: shell
        example: "/bin/bash"
        readOnly: true
  Group:
    type: object
    properties:
      name:
        type: string
        description: Group name
        example: "adm"
        readOnly: true
      gid:
        type: integer
        description: Group identifier
        example: 4
        readOnly: true
      members:
        type: array
        items:
          type: string
          description: User in the group
          example: "syslog"
          readOnly: true
